### ISSUE TITLE
Lerneinheit erstellen: Reiter "sofort"

### ISSUE THREAD

**Issue by mawipp20** [mawipp20/tps#12]
Der Lehrer gibt nur eine Anzahl von Aufgaben an und der Controller erstellt automatisch Tasks mit dem Text "Aufgabe N".

**Comment by y0giBear** [comment]
Felder expiry_minutes und numTeamSize wurden aus lesson_quick entfernt, startKey als hiddenInput hinzugefügt, ebenso $model->beforeValidate() um die lesson mit einem startKey zu versorgen
